---
title: "MCL19 ITS2"
output: html_notebook
---
This is from the Microbial Landscape experiment (summer). ITS2 data from Symportal. 
```{r}
library(tidyverse)
library(readxl)
library(phyloseq)
library(janitor)
```

# Read in coral ITS2 profiles
```{r}
sam0 <- readxl::read_xlsx("MCL_SymPortal_submission_input.xlsx", skip = 1) #Symportal submission form
sam1 <- as.matrix(sam0[, -1])
rownames(sam1) <- sam0$sample_name
sam <- sample_data(data.frame(sam1))

tax0 <- read_tsv(
  file  = "20201214_matsuda_MCL/its2_type_profiles/133_20201216_DBV_20201216T011417.profiles.relative.abund_and_meta.txt",
  n_max = 6) %>%
  dplyr::select(-2) %>% 
  gather(UID, value, -1) %>% 
  spread(1, value) %>%
  clean_names()
tax1 <- as.matrix(tax0[, -1], dimnames = list(tax0$uid, colnames(tax0[-1])))
rownames(tax1) <- tax0$uid
tax <- tax_table(tax1)

otu0 <- read_tsv(
  file  = "20201214_matsuda_MCL/its2_type_profiles/133_20201216_DBV_20201216T011417.profiles.relative.abund_and_meta.txt") %>% 
  rename(sample_name = X2) %>%
  select(-1) %>%
  slice(7:n()) %>%
  mutate_at(2:ncol(.), as.numeric)
otu1 <- as.matrix(otu0[, -1])
rownames(otu1) <- otu0$sample_name
otu <- otu_table(otu1, taxa_are_rows = FALSE)

coral <- phyloseq(otu, tax, sam)
```

# Read in coral post-QC sequence variants
```{r}
sam0 <- read_xlsx("MCL_SymPortal_submission_input.xlsx", skip = 1)
rownames(sam0) <- sam0$sample_name
sam <- sample_data(data.frame(sam0))
taxnames <- read_tsv(
  file  = "20201214_matsuda_MCL/post_med_seqs/133_20201216_DBV_20201216T011417.seqs.relative.abund_only.txt",
  n_max = 0) %>%
  select(-1) %>%
  names(.)
tax0 <- data_frame(
  DIV = taxnames,
  clade = str_extract(DIV, "[A-Z]")
)
tax1 <- as.matrix(tax0)
rownames(tax1) <- tax0$DIV
tax <- tax_table(tax1)
otu0 <- read_tsv(
  file  = "20201214_matsuda_MCL/post_med_seqs/133_20201216_DBV_20201216T011417.seqs.relative.abund_and_meta.txt") %>%
  select(-1, -(3:33))
otu1 <- as.matrix(otu0[, -1])
rownames(otu1) <- otu0$sample_name
otu <- otu_table(otu1, taxa_are_rows = FALSE)
coralDIV <- phyloseq(otu, tax, sam)
```

```{r}
save(coral, coralDIV, file = "data/coral_phyloseq.RData")
```


#Analysis (RCunning Script)
```{r}
library(tidyverse)
library(janitor)
library(phyloseq)  # source('http://bioconductor.org/biocLite.R'); biocLite('phyloseq')
library(zoo)
library(stringr)
library(vegan)
library(multcompView)
# Load data (see data_exploration.Rmd)
load("data/coral_phyloseq.RData")
```

```{r}
coral2 <- coral %>%
  subset_samples(!is.na(host_species))
coralDIV2 <- coralDIV %>%
  subset_samples(!is.na(host_species))
```


```{r, fig.width = 10, fig.height = 40}
# Plot ITS2 profiles for each coral sample by species and site
plot_bar(coral, fill = "its2_type_profile") +
  facet_wrap(~ host_genus + host_species, ncol = 6, scales = "free") +
  #theme(legend.position = "none") +
  geom_bar(stat = "identity")
# Plot all post-MED sequences
plot_bar(coralDIV2, fill = "DIV") +
  facet_wrap(~ host_genus + host_species, scales = "free") +
  #theme(legend.position = "none") +
  geom_bar(stat = "identity")
# Glom all post-MED sequences by clade:
divclades <- coralDIV2 %>%
  tax_glom(taxrank = "clade") %>%                # agglomerate at clade level
  psmelt() %>%                                         # Melt to long format
  arrange(clade)                                      # Sort data frame alphabetically by clade
ggplot(divclades, aes(x = Sample, y = Abundance, fill = clade)) +
  facet_wrap(~ host_genus + host_species, scales = "free") +
  geom_bar(stat = "identity") +
  labs(title=NULL, x = NULL, y = "Relative abundance")
```